project:
  type: website
  render: 
    - "*.qmd"
    - "!/templates"

execute:
  freeze: auto # computational documents re-render only when source changes
  
website: 
  title: "Reproducible Research Workshop"
  navbar: 
    left: 
      - text: Pre-work
        href: index.qmd
      - text: Slides
        menu:
          - text: 1 - Reproducible research
            href: 01-reprores.qmd
          - text: 2 - Hello Quarto
            href: 02-quarto.qmd
      - text: Exercises
        href: 03-exercises.qmd 
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/ellfran-7/repro-research-workshop
  page-footer: "LIEC - CS WORKSHOP, Ellis Franklin"

format:
  html:
    toc: true
    theme: [minty, web-styles.scss]
    grid: 
      body-width: 900px
    



