project:
  type: website
  render: 
    - "index.qmd"
    - "01-reprores-slides.qmd"
    - "02-quarto-page.qmd"
    - "03-post-work.qmd"
    - "04-further-reads.qmd"
    - "!04-exercises-page.qmd"
    - "!02-quarto-slides.qmd"
    - "!templates/"

execute:
  freeze: auto # computational documents re-render only when source changes
  
website: 
  title: "Reproducible Research Workshop"
  navbar: 
    left: 
      - text: Pre-work
        href: index.qmd
      - text: Content
        menu: 
          - text: Repro Research
            href: 01-reprores-slides.qmd
          - text: Quarto
            href: 02-quarto-page.qmd
      - text: Post-work
        href: 03-post-work.qmd
      - text: Resources
        href: 04-further-reads.qmd
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/ellfran-7/repro-research-workshop
  page-footer: 
    left: "© Ellis Franklin, 2025."
    right: "Made with 💚 and Quarto"
  

format:
  html:
    toc: true
    theme: [minty, web-styles.scss]
    grid: 
      body-width: 1000px
    



