project:
  type: website
  output-dir: docs

website: 
  title: "Reproducible Research Workshop"
  navbar: 
    left: 
      - text: Pre-work
        href: index.qmd
    # right: 
    #   - text: Slides
    #     menu: 
    #       - text: 01 - Reproducible research
    #         href: ...
    #       - text: 02 - Quarto
    #         href: ...
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/ellfran-7/repro-research-workshop
  page-footer: "LIEC - CS WORKSHOP, Ellis Franklin"

format:
  html:
    toc: true
    theme: [minty, web-styles.scss]
    grid: 
      body-width: 900px
    



